### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by ghost** [Alexell/ClaytonBOT#1]
Игра обновилась, в боте пошли ошибки соответственно. В конце новой игры, баланс не увеличивается.
Error during game play: 500, message='Internal Server Error', url=URL('https://tonclayton.fun/api/stack/update')

Ещё такие ошибки бывают.
Error starting game: 500, message='Internal Server Error', url=URL('https://tonclayton.fun/api/stack/start')
Unknown error when Claiming: 404, message='Not Found', url=URL('https://tonclayton.fun/api/user/claim-cl')

**Comment by Alexell** [comment]
Это уже пофикшено.
