### ISSUE TITLE
Освежи пожалуйста

### ISSUE THREAD

**Issue by feraggamo** [Alexell/ClaytonBOT#10]
![изображение_2024-09-28_232512769](https://github.com/user-attachments/assets/580aebaa-61a6-4571-adc0-b41b718ca8f5)

**Comment by MelikUltra** [comment]
the api for stack game is changed you have to update it in clamer.py

**Comment by Alexell** [comment]
It's hard to do right now. Clayton doesn't work properly. I see various errors under the hood, for example:
```
failed to connect to `host=localhost user=clayton database=clay_v2`: server error (FATAL: sorry, too many clients already (SQLSTATE 53300))
```
or
```
redis: nil
```

It looks like they have problems with MySQL optimization and maybe Redis is down.

**Comment by Alexell** [comment]
But I'll do it today.

**Comment by MelikUltra** [comment]
> But I'll do it today.

we will be appreciated Boss
