### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by pylogi** [Alexell/ClaytonBOT#2]
![image](https://github.com/user-attachments/assets/9bef01e2-59c1-42b0-82c3-883e8dbaf37a)

**Comment by Zifirlk** [comment]
![image](https://github.com/user-attachments/assets/2d57c5e4-13be-49b5-bca8-68b093116262)

**Comment by Alexell** [comment]
Errors 502 from the Clayton server, the bot has nothing to do with it. The rest of the problems are due to the game update, I fixed them.
