### ISSUE TITLE
не помешает освежить бота :)

### ISSUE THREAD

**Issue by d10nn** [Alexell/ClaytonBOT#5]
![image](https://github.com/user-attachments/assets/96307c52-c3ad-49ed-b165-10192791ba40)

вчера еще работало нормально, сегодня уже насыпает.

**Comment by Alexell** [comment]
Через 2 часа буду у компа, сделаю.

**Comment by Alexell** [comment]
Исправлено. Используйте `git pull` для обновления.

**Comment by d10nn** [comment]
благодарочка
