### ISSUE TITLE
musk

### ISSUE THREAD

**Issue by d10nn** [Alexell/ClaytonBOT#8]
XEmpireBot все? текущей версией еще можно пользоваться?

**Comment by NamasteIndia** [comment]
yes it is working and i am using it ;)

**Comment by d10nn** [comment]
Yeah, but I see the bot's been moved to the archive, so I'm asking

**Comment by Alexell** [comment]
@Defarion пользуйтесь, пока работает. Я же не ломал ее, просто больше не буду поддерживать, т.к. мне от нее никакого проку после того, как меня забанили.

**Comment by d10nn** [comment]
@Alexell проверь своего маска, может разбанили
с утра словил бан, написал в поддержку, час назад меня разбанили (тишина от поддержки)
не знаю как и почему.. может и тебя разбанили

**Comment by HunterTTC98** [comment]
At the session creation part, I waited for a long time but nothing happened.
I have entered the correct API and HASH.
![image](https://github.com/user-attachments/assets/95276809-7b80-4057-afe5-66b3913c44b4)

**Comment by NamasteIndia** [comment]
Try generating session from another bot repo and use those session files here 
sessions/your.SESSION

**Comment by HunterTTC98** [comment]
I tried but when I copied that session file to the bot, it seemed it was incompatible or had a different structure.
That session is only active in the bot that was created.
![image](https://github.com/user-attachments/assets/3da597d5-cc88-4691-b67f-f3173c1bbc98)

**Comment by NamasteIndia** [comment]
Working fine for me, make sure you place them inside the 'sessions' folder then fill the API_ID=65566556 API_HASH=GDGSGGSGS

This way I am running 8 games

Try using the session files with other bots and make sure you copy them properly

**Comment by Alexell** [comment]
@d10nn нет, меня не разбанили, я тоже писал в саппорт, тишина.
