### ISSUE TITLE
вопрос

### ISSUE THREAD

**Issue by rixfou** [Alexell/ClaytonBOT#9]
Алекс, а Вы использовали переговоры в x empire?

**Comment by Alexell** [comment]
Да, но в алмазной лиге от них мне уже не было никакого проку. Там то потеряю 10-50 млн за сессию из 5 матчей, то столько же выиграю. По отношению к ежечасной прибыли, это несущественно и даже не всегда в плюс. А вот на золотой и платине еще была польза.

**Comment by Alexell** [comment]
Можно не писать оффтоп?
